Homework 6
samodur69/AlexeyNadenenko pull request #6
Opened 2021-05-24 07:41 UTC by samodur69

Homework 6 - done. Test runs in headless mode. It can be changed in test.properties file.

2021-05-26 18:57 UTC, shoggy requested changes
chromedriver is not killed after test execution

2021-05-26 18:57 UTC, shoggy commented on pom.xml
> +        </dependency>
[The Pink Panther Theme Song](https://youtu.be/ZWo0gm2F55s?t=3) (To-Do-to-do...)

2021-05-26 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw6/entities/MetalAndColor.java
> +    }
Since you use Lombok this methods can be avoided
Look for [lombok.Data](https://projectlombok.org/features/Data)

2021-05-26 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw6/entities/User.java
> +    }
Can be avoided 
look for `lombok.experimental.Value`

2021-05-26 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw6/site/components/Results.java
> +    public static Text vegetables;
This approach can be simplified by using List

2021-05-26 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw6/site/components/Results.java
> +    }
Methods look almost identical, avoid duplication

2021-05-26 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw6/test/BaseTest.java
> +}
This interface looks like unused

2021-05-27 08:00 UTC, samodur69 commented on src/test/java/ru/training/at/hw6/entities/MetalAndColor.java
> +    }
I use this method only for debug and forgot to delete. Fixed

2021-05-27 08:00 UTC, samodur69 commented on pom.xml
> +        </dependency>
fixed

2021-05-27 08:12 UTC, samodur69 commented on src/test/java/ru/training/at/hw6/entities/User.java
> +    }
Fixed

2021-05-27 08:24 UTC, samodur69 commented on src/test/java/ru/training/at/hw6/test/BaseTest.java
> +}
I spent a lot of time to fix bug with closing drivers.... and just forgot to implement Interface in Test class.

Fixed

2021-05-27 08:52 UTC, samodur69 commented on src/test/java/ru/training/at/hw6/site/components/Results.java
> +    public static Text vegetables;
Sure, but in this case I have direct access to the element and I don't need to remember the indexes in the array. As an example - the layout has changed and the elements have been swapped. It's clear that it can be simplified, but I wanted to use framework features in using Text object and Section class. 

This approach made the test even more illustrative.
`sa.assertEquals(Results.getSummary(), Arrays.stream(testData.getSummary()).sum());
        sa.assertEquals(getTextElementValuesArray(elements), testData.getElements());
        sa.assertEquals(getTextElementValue(color), testData.getColor());`

2021-05-27 08:57 UTC, samodur69 commented on src/test/java/ru/training/at/hw6/site/components/Results.java
> +    }
fixed

2021-05-28 07:13 UTC, shoggy approved these changes

2021-05-28 07:23 UTC, merged